trigger:
- none

resources:
- repo: self

variables:
  containerRegistryName: 'dssdemoregnovanitha'
  kubernetesClusterName: "dssaksclusternovanitha"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      inputs:
        targetFiles: '$(Build.SourcesDirectory)/**/CreateAKSCluster-parameters.json'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        useLegacyPattern: false
        enableTelemetry: true
    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Pass - Sponsorship(66203593-eb00-4e9b-9838-089b29e946d7)'
        subscriptionId: '66203593-eb00-4e9b-9838-089b29e946d7'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Demo-rg'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/**/CreateAKSCluster.json'
        csmParametersFile: '$(Build.SourcesDirectory)/**/CreateAKSCluster-parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'AKSCluster'