trigger:
- none

resources:
- repo: self

variables:
  containerRegistryName: 'dssdemoregnovdivya'
  kubernetesClusterName: "dssaksclusternovdivya"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: replacetokens@4
      inputs:
        targetFiles: '$(Build.SourcesDirectory)/**/CreateAKSCluster-parameters.json'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        useLegacyPattern: false
        enableTelemetry: true
    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Pass - Sponsorship(70d03302-80d0-4597-ba74-e01b99ca052b)'
        subscriptionId: '70d03302-80d0-4597-ba74-e01b99ca052b'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Demo-rg'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/**/CreateAKSCluster.json'
        csmParametersFile: '$(Build.SourcesDirectory)/**/CreateAKSCluster-parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'AKSCluster'
       