apiVersion: v1
kind: Service
metadata:
  name: hellowebapp
spec:
  type: LoadBalancer
  ports:
  - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: hellowebapp
